name: Generate PDF

on:
  push:
    branches:
      - trial

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-xetex texlive-latex-extra texlive-fonts-extra fonts-noto-color-emoji

    - name: Convert Markdown to PDF
      run: |
        pandoc index.md -o your_cv.pdf --pdf-engine=xelatex -V mainfont="Noto Color Emoji"
    
    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: CV-PDF
        path: butriman_cv.pdf
